# Weather Point
train:
  epochs: 300
  batch_size: 16
  lr: 1.0e-3
  alpha: 1
  beta: 5

diffusion:
  seqlen: 24
  layers: 4
  channels: 64
  nheads: 8
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.2
  num_steps: 50
  schedule: "quad"

model:
  timeemb: 128
  featureemb: 16
